---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, tiering' 
summary: Cloud Tiering의 새로운 기능 알아보기 
---
= Cloud Tiering의 새로운 기능
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Tiering의 새로운 기능 알아보기



== 2022년 4월 4일



=== 이제 Amazon S3 Glacier Instant Retrieval 저장소 클래스를 사용할 수 있습니다.

Cloud Tiering을 설정할 때 특정 일 수 후에 비활성 데이터가 _Standard_storage 클래스에서 _Glacier Instant Retrieval_로 전환되도록 수명주기 규칙을 구성할 수 있습니다. 이를 통해 AWS 인프라 비용을 절감할 수 있습니다.



== 2021년 9월 2일



=== Cloud Tiering BYOL 라이센스는 FabricPool 라이센스를 대체합니다.

이제 Cloud Tiering 서비스를 사용하여 Cloud Manager 내에서 지원되는 계층화 구성에 새로운 * Cloud Tiering * 라이센스를 사용할 수 있습니다. 여러 온프레미스 ONTAP 클러스터에서 사용할 수 있는 부동 라이센스입니다. 이전에 사용했을 수 있는 * FabricPool * 라이센스는 Cloud Manager 내에서 지원되지 않는 구성에만 유지됩니다.

https://docs.netapp.com/us-en/cloud-manager-tiering/task-licensing-cloud-tiering.html#use-a-cloud-tiering-byol-license["새로운 Cloud Tiering 라이센스에 대해 자세히 알아보십시오"].



=== 사내 ONTAP 클러스터에서 S3 호환 오브젝트 스토리지로 비활성 데이터 계층화

이제 S3(Simple Storage Service) 프로토콜을 사용하는 오브젝트 스토리지 서비스에 비활성 데이터를 계층화할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-tiering/task-tiering-onprem-s3-compat.html["데이터를 S3 호환 오브젝트 스토리지에 계층화하는 방법을 알아보십시오"].



== 2021년 7월 7일



=== Connector는 Azure Blob 저장소에 데이터를 계층화할 때 사내에서 실행할 수 있습니다.

Azure VNET에 설치된 커넥터를 더 이상 사용할 필요가 없습니다. Azure Blob 저장소에 데이터를 계층화할 때 Connector를 사내 호스트에서 실행할 수 있습니다.



== 2021년 6월 7일



=== 이제 특정 클라우드 공급자 스토리지에 새로운 계층화 클래스를 사용할 수 있습니다.

이전 릴리스에서는 Amazon S3 또는 Google Cloud 오브젝트 스토리지를 사용하는 경우 30일 후에 표준 스토리지 클래스에서 다른 스토리지 클래스로 계층적 데이터를 전환할 수 있었습니다. 이 릴리즈에는 몇 가지 새로운 기능이 추가되었습니다.

* 계층형 데이터를 보다 비용 효율적인 계층으로 이동하는 일 수를 선택할 수 있습니다. 이를 데이터 "라이프사이클 관리"라고 합니다.
* Azure Blob은 이제 _Cool_access 계층을 지원합니다.
* Google Cloud Storage는 시간에 따라 계층화된 데이터를 여러 스토리지 계층으로 이동할 수 있도록 지원합니다. 예를 들어 45일 후에 _Standard_class에서 _Nearline_class로 계층화된 데이터를 이동한 다음 75일 후에 _Coldline_class로 이동한 다음 270일 후에 _Archive_class로 이동할 수 있습니다.




=== 이제 클라우드 계층에서 성능 계층으로 데이터를 사전 예방적으로 이동할 수 있습니다.

이 기능은 볼륨에 대한 계층화 사용을 중단하거나 모든 사용자 데이터를 성능 계층에 유지하되 스냅샷 복사본을 클라우드 계층에 보관하려는 경우에 유용합니다. 이 기능은 ONTAP 9.8 이상을 사용할 때 사용할 수 있습니다.

자세한 내용은 를 참조하십시오 link:task-managing-tiering.html#migrating-data-from-the-cloud-tier-back-to-the-performance-tier["데이터를 성능 계층으로 다시 마이그레이션"].



== 2021년 5월 2일



=== 이제 계층화 정책을 적용할 때 모든 볼륨을 선택할 수 있습니다.

ONTAP 시스템에서 계층화할 볼륨을 선택할 때 이제 Tier Volumes 페이지에서 * All * volumes를 선택하여 모든 볼륨에 동일한 정책을 쉽게 적용할 수 있는 확인란이 있습니다. link:task-managing-tiering.html#tiering-data-from-additional-volumes["클러스터의 모든 볼륨을 선택하는 방법을 알아봅니다"].



=== 이제 "냉각" 일 수를 183일로 설정할 수 있습니다.

ONTAP 9.8 이상을 사용할 때 볼륨의 데이터를 오브젝트 스토리지로 이동하기 전에 비활성 상태로 유지해야 하는 기간을 결정하는 "냉각 일" 수를 변경해야 하는 경우 최대 183일(최대 63일)까지 지정할 수 있습니다.



== 2021년 3월 8일



=== Google 클라우드 스토리지로 계층화할 때 라이프사이클 규칙을 사용할 수 있습니다.

Google Cloud Storage로 계층화할 때 30일 후에 계층형 데이터가 Standard 스토리지 클래스에서 저비용 Nearline, Coldline 또는 아카이브 스토리지로 전환되도록 수명주기 규칙을 적용할 수 있습니다.
